version: '3'

services:
  plex:
    container_name: plex
    image: plexinc/pms-docker
    restart: unless-stopped
    network_mode: host
    environment:
      TZ: Europe/London
    labels:
      traefik.enable: true
      traefik.http.services.plex.loadbalancer.server.port: 32400
      traefik.http.routers.plex.rule: Host(`plex`)
    volumes:
      - /containers/plex:/config
      - /tmp/transcode:/transcode
      - /tank/media/movies:/tank/media/movies:ro
      - /tank/media/tv:/tank/media/tv:ro
      - /tank/media/music:/tank/media/music:ro
      - /tank/media/videos:/tank/media/videos:ro
      - /tank/media/sport:/tank/media/sport
    devices:
      - /dev/dri:/dev/dri
