services:
  plex:
    container_name: plex
    image: plexinc/pms-docker
    restart: unless-stopped
    network_mode: host
    environment:
      TZ: Europe/London
      PLEX_UID: 991
      PLEX_GID: 994
    volumes:
      - /containers/plex:/config
      - /tmp/plex:/transcode
      - /tank/media/movies:/tank/media/movies
      - /tank/media/tv:/tank/media/tv
      - /tank/media/music:/tank/media/music
      - /tank/media/videos:/tank/media/videos
      - /tank/media/sport:/tank/media/sport
      - /tank/media/sport_archive:/tank/media/sport_archive
    devices:
      - /dev/dri:/dev/dri
